### ISSUE TITLE
Taks appearing replicated on the dashboard

### ISSUE THREAD

**Issue by IgorVictor** [fogbow/arrebol#21]
Tasks are appearing on unrelated jobs when requested

**Comment by IgorVictor** [comment]
Could not reproduce

**Comment by thiagomanel** [comment]
The bug was identified by @fubica 
In summary, the same task appeared both as "Completed" and "failed". We guess the bug is related to the mechanism of replicating failed tasks. We could not reproduce it with the new code base yet (the bug was discovered with the pre-refactoring code).

**Comment by fubica** [comment]
On Jun 27, 2016, at 11:11 , Thiago Emmanuel Pereira notifications@github.com wrote:

> The bug was identified by @fubica 
> In summary, the same task appeared both as "Completed" and "failed". We guess the bug is related to the mechanism of replicating failed tasks. However, we could not reproduce it with the new code base yet (the bug was discovered with the pre-refactoring code).
> 
> In fact, the description of the bug is a bit different. There is no problem in a task appearing as both completed and failed, provided that is appears only once as completed. The bug is that the same task appears multiple times as completed. This happen in a scenario where multiple tasks have failed at least once. I don't remember if all tasks that appeared completed multiple times, also appeared as failed, but it seems that there is a clear correlation between tasks failing and the appearance of this bug. Hopefully it has been fixed as a collateral effect of other bug fixes.

---

 Francisco Vilar Brasileiro                                   VoIP:  +55 83 1075 2038
 Departamento de Sistemas e Computação   Fone:  +55 83 2101 1644
 Universidade Federal de Campina Grande   Fax:    +55 83 2101 1498
 58.429-900, Campina Grande, PB, Brasil      E-mail: fubica@dsc.ufcg.edu.br
