### ISSUE TITLE
Completed jobs are being "re-added" on restart

### ISSUE THREAD

**Issue by IgorVictor** [fogbow/arrebol#47]
To reproduce:
Create a job
Wait for completion
kill arrebol+blowout
restart arrebol
The job should be back on the queue in a ready state

**Comment by IgorVictor** [comment]
When this job completes, it goes to the Not created state. So that's the origin of that bug

**Comment by hukasu** [comment]
The state shows as Not Created because it is not re-added to the task pool, which is the intended behavior, the only issue is setting the state to COMPLETED after reloading job from DB
